apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartwish-frontend
  labels:
    app: cartwish-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cartwish-frontend
  template:
    metadata:
      labels:
        app: cartwish-frontend
    spec:
      containers:
        - name: cartwish-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}