apiVersion: v1
kind: Service
metadata:
  name: cartwish-frontend-service
spec:
  selector:
    app: cartwish-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
  type: {{ .Values.service.type }}