apiVersion: v1
kind: Service
metadata:
  name: cartwish-frontend-service
spec:
  selector:
    app: cartwish-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
